### ISSUE TITLE
MissingMethodException on Uno WebAssembly

### ISSUE THREAD

**Issue by Arlodotexe** [mono/taglib-sharp#278]
When scanning a file on WebAssembly via Uno Platform, the following error is logged:
> dotnet.js:1 ThreadPool Callback threw an unhandled exception of type System.MissingMethodException

Full, minimal repro here:
[TagLibSharpOnUnoWasm.zip](https://github.com/mono/taglib-sharp/files/7468072/TagLibSharpOnUnoWasm.zip)

I've tested UWP and Android, both are working as expected. This issue only occurs when running in the browser.

**Comment by Arlodotexe** [comment]
Wrapping the method call in a try/catch gives us a bit more insight: 

```
System.MissingMethodException: MissingConstructor_Name, TagLib.Mpeg.AudioFile
dotnet.js:1    at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\mono\System.Private.CoreLib\src\System\RuntimeType.Mono.cs:line 1499
dotnet.js:1    at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.RuntimeType.cs:line 36
dotnet.js:1    at System.Activator.CreateInstance(Type type, Object[] args) in D:\a\Uno.DotnetRuntime.WebAssembly\Uno.DotnetRuntime.WebAssembly\runtime\src\libraries\System.Private.CoreLib\src\System\Activator.cs:line 31
dotnet.js:1    at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle) in B:\dev\netstandard\taglib-sharp\src\TaglibSharp\File.cs:line 1297
dotnet.js:1    at TagLibSharpOnUnoWasm.MainPage.<Button_Click>d__5.MoveNext() in B:\dev\uwp\Throwaway Projects\TagLibSharpOnUnoWasm\TagLibSharpOnUnoWasm.Shared\MainPage.xaml.cs:line 63
```

**Comment by Arlodotexe** [comment]
As a temporary workaround, you can prevent TagLib from using `Activator.CreateInstance` by creating your own FileTypeResolver.

```csharp
// Manual resolving based on mime type.
// Must pass mime type to File.Create(), resolving based on file extension not handled here.
TagLib.File.AddFileTypeResolver((abstr, mimeType, readStyle) => mimeType switch
{
    // Aac
    "audio/aac" => new TagLib.Aac.File(abstr, readStyle),

    // Aiff
    "audio/x-aiff" => new TagLib.Aiff.File(abstr, readStyle),
    "audio/aiff" => new TagLib.Aiff.File(abstr, readStyle),
    "sound/aiff" => new TagLib.Aiff.File(abstr, readStyle),
    "application/x-aiff" => new TagLib.Aiff.File(abstr, readStyle),

    // Ape
    "audio/x-ape" => new TagLib.Ape.File(abstr, readStyle),
    "audio/ape" => new TagLib.Ape.File(abstr, readStyle),
    "application/x-ape" => new TagLib.Ape.File(abstr, readStyle),

    // Asf
    "audio/x-ms-wma" => new TagLib.Asf.File(abstr, readStyle),
    "audio/x-ms-asf" => new TagLib.Asf.File(abstr, readStyle),
    "video/x-ms-asf" => new TagLib.Asf.File(abstr, readStyle),

    // Audible
    "audio/x-audible" => new TagLib.Audible.File(abstr, readStyle),

    // Dsf
    "audio/x-dsf" => new TagLib.Dsf.File(abstr, readStyle),
    "audio/dsf" => new TagLib.Dsf.File(abstr, readStyle),
    "sound/dsf" => new TagLib.Dsf.File(abstr, readStyle),
    "application/x-dsf" => new TagLib.Dsf.File(abstr, readStyle),

    // Flac
    "audio/x-flac" => new TagLib.Flac.File(abstr, readStyle),
    "application/x-flac" => new TagLib.Flac.File(abstr, readStyle),
    "audio/flac" => new TagLib.Flac.File(abstr, readStyle),

    // gif
    "image/gif" => new TagLib.Gif.File(abstr, readStyle),

    // Image.NoMetadata
    "image/x-MS-bmp" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-bmp" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-portable-pixmap" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-portable-graymap" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-portable-bitmap" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-portable-anymap" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/x-pcx" => new TagLib.Image.NoMetadata.File(abstr, readStyle),
    "image/svg+xml" => new TagLib.Image.NoMetadata.File(abstr, readStyle),

    // Jpeg
    "image/jpeg" => new TagLib.Jpeg.File(abstr, readStyle),

    // Matroska
    "video/webm" => new TagLib.Matroska.File(abstr, readStyle),
    "video/x-matroska" => new TagLib.Matroska.File(abstr, readStyle),

    // MusePack
    "audio/x-musepack" => new TagLib.MusePack.File(abstr, readStyle),

    // Mpeg
    "audio/x-mp3" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "application/x-id3" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/mpeg" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/x-mpeg" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/x-mpeg-3" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/mpeg3" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/mp3" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/x-mp2" => new TagLib.Mpeg.AudioFile(abstr, readStyle),
    "audio/x-mp1" => new TagLib.Mpeg.AudioFile(abstr, readStyle),

    "video/x-mpg" => new TagLib.Mpeg.File(abstr, readStyle),
    "video/mpeg" => new TagLib.Mpeg.File(abstr, readStyle),

    // Mpeg4
    "audio/mp4" => new TagLib.Mpeg4.File(abstr, readStyle),
    "audio/x-m4a" => new TagLib.Mpeg4.File(abstr, readStyle),
    "video/mp4" => new TagLib.Mpeg4.File(abstr, readStyle),
    "video/x-m4v" => new TagLib.Mpeg4.File(abstr, readStyle),

    // Ogg
    "application/ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "application/x-ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/vorbis" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/x-vorbis" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/x-vorbis+ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/x-ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "video/ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "video/x-ogm+ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "video/x-theora+ogg" => new TagLib.Ogg.File(abstr, readStyle),
    "video/x-theora" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/opus" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/x-opus" => new TagLib.Ogg.File(abstr, readStyle),
    "audio/x-opus+ogg" => new TagLib.Ogg.File(abstr, readStyle),

    // Png
    "image/png" => new TagLib.Png.File(abstr, readStyle),

    // Riff
    "video/avi" => new TagLib.Riff.File(abstr, readStyle),
    "video/msvideo" => new TagLib.Riff.File(abstr, readStyle),
    "video/x-msvideo" => new TagLib.Riff.File(abstr, readStyle),
    "image/avi" => new TagLib.Riff.File(abstr, readStyle),
    "application/x-troff-msvideo" => new TagLib.Riff.File(abstr, readStyle),
    "audio/avi" => new TagLib.Riff.File(abstr, readStyle),
    "audio/wav" => new TagLib.Riff.File(abstr, readStyle),
    "audio/wave" => new TagLib.Riff.File(abstr, readStyle),
    "audio/x-wav" => new TagLib.Riff.File(abstr, readStyle),

    // Tiff.Arw
    "image/arw" => new TagLib.Tiff.Arw.File(abstr, readStyle),
    "image/x-sony-arw" => new TagLib.Tiff.Arw.File(abstr, readStyle),

    // Tiff.Cr2
    "image/cr2" => new TagLib.Tiff.Cr2.File(abstr, readStyle),
    "image/x-cannon-cr2" => new TagLib.Tiff.Cr2.File(abstr, readStyle),

    // Tiff.Dng
    "image/dng" => new TagLib.Tiff.Dng.File(abstr, readStyle),
    "image/x-adobe-dng" => new TagLib.Tiff.Dng.File(abstr, readStyle),

    // Tiff.Nef
    "image/nef" => new TagLib.Tiff.Nef.File(abstr, readStyle),
    "image/x-nikon-nef" => new TagLib.Tiff.Nef.File(abstr, readStyle),

    // Tiff.Pef
    "image/pef" => new TagLib.Tiff.Pef.File(abstr, readStyle),
    "image/x-pentax-pef" => new TagLib.Tiff.Pef.File(abstr, readStyle),

    // Tiff.Rw2
    "image/rw2" => new TagLib.Tiff.Rw2.File(abstr, readStyle),
    "image/raw" => new TagLib.Tiff.Rw2.File(abstr, readStyle),
    "image/x-raw" => new TagLib.Tiff.Rw2.File(abstr, readStyle),
    "image/x-panasonic-raw" => new TagLib.Tiff.Rw2.File(abstr, readStyle),

    // Tiff
    "image/tiff" => new TagLib.Tiff.File(abstr, readStyle),

    // WavPack
    "audio/x-wavpack" => new TagLib.WavPack.File(abstr, readStyle),

    _ => null,
});
```

**Comment by midn1** [comment]
I just came across this problem while working on a different project. There's absolutely no info about this error online. Do you have an MVE perchance to pass onto the dotnet/runtime issue tracker?
